...@style.d2

# -----------------------------------------------------------------------------
# General Prompts
# -----------------------------------------------------------------------------
pm: "Prompt Maker : Specialized Prompts" 
cs: "Conversation Summarizer : Context Prompts" 
sg: "Schema Generator : Context Prompts" 
cm: "Commit Message Generator : Specialized Prompts" 
qa: "Questions and Answers : Specialized Prompts" 
ld: "Language Definitions Generator : Specialized Prompts" 
hm: "Homework Maker : Specialized Prompts"

# -----------------------------------------------------------------------------
# Social Prompts
# -----------------------------------------------------------------------------

pr: "Public Relations Manager : Multiperspective Prompts"

# -----------------------------------------------------------------------------
# Programming Oriented Prompts
# -----------------------------------------------------------------------------

sre: "Requirements Engineer : Specialized Prompts"

sse: "Systems Engineer : Multiperspective Prompts"

# -----------------------------------------------------------------------------
# Prompts Designed specifically to be a template of business, may be refined
# to fit an specific business entity (organization/person)
# -----------------------------------------------------------------------------

bexec: "Business Chief Officers : Multiperspective Prompts"

# -----------------------------------------------------------------------------
# Relationships
# -----------------------------------------------------------------------------

# The use of the "*" wildcard means that it applies to all objects in the file
# for example: "object -- *: something" means that said object interacts as
# described with every single object on this file

cs -- *: "Summarizes all the provided conversations in a single file"
sg -- pm: "Generates and output schema for a new prompt"
