{ config, lib, pkgs, inputs, ... }:
{
  config = {
    environment.systemPackages = with pkgs; [
      floorp
      firefox
      #openscad
      #freecad
      #brlcad
      kitty
      foot
      tuba
      vesktop
      whatsapp-for-linux
      telegram-desktop
      #evolution
      p7zip
      collision
      gnome-decoder
      neovim
      bruno
      sequeler
      citations
      libreoffice
      varia
      parabolic
      aria
      foliate
      gnucash
      prismlauncher
      cool-retro-term
      nethack
      shattered-pixel-dungeon
      git
      imagemagickBig
      conjure
      krita
      inkscape
      switcheroo
      ventoy
      dialect
      eartag
      paper-clip
      #blender
      bisq-desktop
      monero-gui
      clapper
      citations
      logseq
      geogebra
      gnome-graphs
      blanket
      solanum
      gnome-obfuscate
      metadata-cleaner
      gnupg
      gnome.gnome-software
      pika-backup
      gnome-secrets
      ffmpeg-full
      video-trimmer
      pitivi
      freetube
      newsflash
      wike
      amberol
      brasero
      colmena
      evolution
      gnupg
      keeweb
      ldns
      nmap
      pomodoro-gtk
      solanum
      rdap
      whois
      wireguard-tools
      yt-dlp
      inputs.zen-browser.packages."${system}".generic
    ];
  };
}
