# Executes commands at start. Typically used to autostart graphical sessions
# and set session-wide enviroment variables
# Will be read when starting as a login shell
export npm_config_prefix="$HOME/.local"
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="${PATH}:$HOME/.local/bin/:$GEM_HOME/bin"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"
export XDG_CONFIG_HOME="$HOME/.config"    
export XDG_CACHE_HOME="$HOME/.cache"       
export XDG_DATA_HOME="$HOME/.local/share"

startx
