# Set enviroments variables. Should not contain commands that produces output
# Will always be read
export EDITOR='nvim'
export VISUAL='nvim'
export BROWSER='microsoft-edge-stable'
export PAGER='less'
export TERMINAL='st'
export SHELL='zsh'

# Wine prefix
export WINEPREFIX="${XDG_DATA_HOME}/wineprefixes/defecto"
# Textnote directory
export TEXTNOTE_DIR="${XDG_DATA_HOME}/textnote/"
