# Executes commands and set confidurations for interactives shell use
# Will be read when starting as a interactive shell
HISTFILE=~/.cache/zsh/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
unsetopt nomatch
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/chiguire/.config/zsh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#### Colors ####
. ~/.cache/wal/colors.sh
printf $(cat ~/.cache/wal/sequences)

#### Aliases ####
# Reload zsh
alias rzsh='source ~/.config/zsh/.zshrc'
# Launch dmenu with custom colors and font
alias dmenu="dmenu -fn Unifont:pixelsize=24 -nb \"$color0\" -nf \"$color15\" \
	-sb \"$color1\" -sf \"$color15\""
# Launch sakis3g with console interface
alias sakis3gz="sudo sakis3gz --interactive console"
# List files with colors
alias ls='ls --color=always'
# List all files with colors
alias la='ls -a --color=always'
# Download
alias a2='aria2c -d ~/Downloads -j 4 -x 6 -m 0 --seed-time=0'
# Download from the links listed in ~/Downloads/.list
alias a2f='a2 --input-file=${HOME}/Downloads/.list'
# Edit ~/Downloads/.list
alias dlist='nvim ~/Downloads/.list'
# Edit current folder's download list
alias edlist='nvim ./.list'
# Download the videos/playlist listed in the folder's list
alias ytdl='yt-dlp --yes-playlist --download-archive ./.listd -a ./.list'
alias ytlist='ytdl -o ./%(playlist_title)s/%(title)s.%(ext)s'
alias yts="yt-dlp -f 'mp4[height<=480]/bv[height<=480]+ba' --merge-output-format mp4"
alias ytal='yt-dlp -f "m4a/ba" -o "%(playlist)s/%(title)s.%(ext)s"'
alias yta='yt-dlp -f "m4a/ba" -o %(title)s.%(ext)s'
alias ytalmp3='yt-dlp -f "mp3" -o "%(playlist)s/%(title)s.%(ext)s"'
alias ytamp3='yt-dlp -f "mp3"'
alias ytchannelbatch="yt-dlp -f 'mp4[height<=480]/bv[height<=480]+ba' --merge-output-format mp4 -o './%(channel)s/%(video_autonumber)04d.%(title)s.%(ext)s' -a"
# neocities
alias neo='bashcities -p carmelomaita'

## Shortcuts to folders ##
alias cdt='cd /home/chiguire/software/trabajo'
alias cdtp='cd /home/chiguire/software/trabajo/pierina/mumu'
alias cdei='/home/chiguire/Documents/estudios/universidad/psm-ing-sistemas/'

## College
college='/home/chiguire/Documents/estudios/universidad/psm-ing-sistemas'
alias mover-d='mv $XDG_DOWNLOAD_DIR/*.{zip,docx,doc,pdf,xls,xlsx,ppt,pptx,rar,png,jpg,jpeg,mp4,mp3,m4a} -t ./'
alias mover-s='mv $XDG_PICTURES_DIR/screenshots/* -t ./'
crear-s () {
	args="$@"
	mkdir -p "$college/$args/{evidencia,materias,pagos,tareas-por-entregar}"
}
crear-m () {
	args="$@"
	mkdir -p "$college/{$args}/{01-corte,02-corte,03-corte,evidencia}/{material,asignaciones/{asignaciones,instrucciones}}"
}

#### Functions ####
## Launchers ##
# Zathura
zathura () {
	nohup tabbed -c zathura $@ -e > /dev/null &
}
## Utilities ##
# Get rows and columns of the terminal
getrc () {
	read -r rows cols < <(stty size)
}
# Clear screen and list files
cls () {
	getrc;
	clear;
	pwd;
	printf '-%.0s' {1..$cols};
	ls;
	printf '-%.0s' {1..$cols};
}
# Clear screen and list all files
cla () {
	getrc;
	clear;
	pwd;
	printf '-%.0s' {1..$cols};
	la;
	printf '-%.0s' {1..$cols};
}
