header:
  prefix: ""
  suffix: ""
  trailingNewlines: 1
  timeFormat: '[Mon] 02 Jan 2006'
section:
  prefix: ___
  suffix: ___
  trailingNewlines: 3
  names:
  - TODO
  - DONE
  - NOTES
file:
  ext: txt
  timeFormat: "2006-01-02"
  cursorLine: 4
archive:
  afterDays: 14
  filePrefix: archive-
  headerPrefix: 'ARCHIVE '
  headerSuffix: ""
  sectionContentPrefix: '['
  sectionContentSuffix: ']'
  sectionContentTimeFormat: "2006-01-02"
  monthTimeFormat: Jan2006
cli:
  timeFormat: "2006-01-02"
